---
title: "make_summarized_exp_object"
author: "avanvalken"
date: "2024-10-07"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(SummarizedExperiment)
knitr::opts_chunk$set(echo = TRUE)
```


# Load data
```{r}
counts <- read.table("../data/rsubread_features_combined.txt",header=T, sep="\t" )
subjdata <- readxl::read_xlsx("../data/RNA_seq_Subject_data.xlsx")
subjdata.v6.1 <- read_excel("../data/RNA_seq_Subject_data_visit_6.xlsx")
subjdata.v6 <- read_excel("../data/RNA_seq_V6BMI.xlsx")

```


## process subjdata
```{r}
# select for processing
df <- subjdata %>% 
               dplyr::select(c(`TB LION ID Number:`, GENDER, AGE, BMI, HELMINTH)) %>% 
               data.table::setnames("TB LION ID Number:", "ID") %>% 
               mutate(nutrition=ifelse(BMI<18.5, "mal", "well"),
                      status=tolower(paste(HELMINTH, nutrition, sep="_")),
                      ID2=gsub("-","",ID),
                      ID2=gsub("LION","LION_",ID2)) 
## still need- diabetes (blood sugar); smoking, risky alcohol score, and BMI-change at each visit

# names of counts file 
x <- colnames(counts)
#x <- x[-c(1:2)]

# make coldata
df.1 <- data.frame(subjid=x) 
df.1$subjid <- toupper(df.1$subjid)

df.1 <- df.1 %>% mutate(ID1=stringr::str_split_i(subjid, "_", i=2),
                        ID1=paste("LION", ID1, sep="_"),
                        visit=stringr::str_split_i(subjid, "_", i=4),
                        visit=gsub("8","1",visit),
                        visit=paste("Visit", visit, sep="_"))
any(df.1$ID1 %in% df$ID2) # TRUE
all(df$ID2 %in% df.1$ID1) # FALSE

y <- setdiff(df.1$ID1, df$ID2)
y
#"LION_0054500940LB" "LION_0238000313LB" "LION_043800678LB"  "LION_37500599LB" 
z <- setdiff(df$ID2, df.1$ID1)
z
#"LION_037500599LB" "LION_043200678LB"

## samples that rsubread had issues with:
#"LION_032500502LB_VSIT_6"  "LION_033300511LB_VISIT_6" "LION_044800738LB_VISIT_6"
```

```{r}
## Probably the correct names that were wrong in the counts file
c("LION_054500940LB", "LION_023800313LB", "LION_043200678LB", "LION_037500599LB")

## change to correct ID
df.1$ID1 <- gsub("LION_0054500940LB","LION_054500940LB", df.1$ID1)
df.1$ID1 <- gsub("LION_0238000313LB","LION_023800313LB", df.1$ID1)
df.1$ID1 <- gsub("LION_043800678LB","LION_043200678LB", df.1$ID1)
df.1$ID1 <- gsub("LION_37500599LB","LION_037500599LB", df.1$ID1)
df.1 <- dplyr::filter(df.1, ID1 != "LION_032500502LB")
df <- dplyr::filter(df, ID2!= "LION_032500502LB")
# check if correct
any(df.1$ID1 %in% df$ID2) # TRUE
all(df.1$ID1 %in% df$ID2) # TRUE
all(df$ID2 %in% df.1$ID1) # TRUE
```
## fix colnames of counts object
```{r}
x <- colnames(counts)

x <- gsub("LION_0054500940LB","LION_054500940LB", x)
x <- gsub("LION_0238000313LB","LION_023800313LB", x)
x <- gsub("LION_043800678LB","LION_043200678LB", x)
x <- gsub("LION_37500599LB","LION_037500599LB", x)
x <- toupper(x)

colnames(counts) <- x

```


```{r}
x <- colnames(counts)
#x <- x[-c(1:2)]
colnames(counts) <- gsub("VISIT_7", "VISIT_6", colnames(counts))
# make coldata
df.1 <- data.frame(subjid=x) 
df.1$subjid <- toupper(df.1$subjid)

df.1 <- df.1 %>% mutate(ID1=stringr::str_split_i(subjid, "_", i=2),
                        ID1=paste("LION", ID1, sep="_"),
                        visit=stringr::str_split_i(subjid, "_", i=4),
                        visit=gsub("8","1",visit),
                        visit=paste("Visit", visit, sep="_"))
# match df.1 to df 
coldata <- merge(df.1, df, by.x="ID1", by.y="ID2")

coldata <- coldata %>% 
               relocate(subjid, .before="ID1") %>% 
               relocate(visit, .before=status) 
coldata$visit <- gsub("Visit_7", "VISIT_6", coldata$visit)
coldata$subjid <- gsub("VISIT_7", "VISIT_6", coldata$subjid)
coldata$subjid <- gsub("WEEK_8", "VISIT_1", coldata$subjid)
colnames(counts) <- gsub("WEEK_8", "VISIT_1", colnames(counts))
colnames(counts) <- toupper(colnames(counts))

all(colnames(counts) %in% coldata$subjid)
all(coldata$subjid %in% colnames(counts))
counts2 <- counts[,coldata$subjid]
all(colnames(counts2) == coldata$subjid)

```

## updata visit_6 BMI
```{r}
# original V6
df <- coldata %>% 
               filter(visit=="Visit_6")
# extract new V6 data
#df.2 <- subjdata.v6 %>% select(c("TB LION ID Number:", "BMI", "HELMINTH" ))
df.2 <- subjdata.v6 %>% select(c("ID", "BMI"))


df.3 <- merge(df, df.2, by.x="ID", by.y="ID")
df.3$BMI.x <- NULL

# Get corrected V6 BMI's and merge with V1
v6 <- df.3 %>% rename("BMI.y"="BMI")
v1 <- coldata %>% filter(visit=="Visit_1")

combined <- rbind(v1, v6)


df.4 <- (select(coldata, c("ID",  "BMI")))
df.5 <- df.4 %>% distinct(.keep_all=T)
df.6 <- filter(df.4, duplicated(df.4)==F)

df.6 <- df.4[!(duplicated(df.4) | duplicated(df.4, fromLast = TRUE)), ]
```

```{r}
df <- as.data.frame(colData(se))
x <- df$subjid
y <- combined$subjid

z <- setdiff(x,y)
z
```
### For now, include z
```{r}
z <- dplyr::filter(df, subjid %in% z)

coldata.1 <- rbind(combined, z)
```




## Filter for only protein coding genes
```{r}
library(EnsDb.Hsapiens.v86)
gns <- genes(EnsDb.Hsapiens.v86)
gns2 <- gns[gns$gene_biotype %in% "protein_coding"]

counts2 <- dplyr::filter(counts2, rownames(counts2) %in% gns2$gene_name)

```



```{r}
rownames(coldata.1) <- coldata.1$subjid
all(colnames(counts2) %in% rownames(coldata.1))
counts2 <- counts2[,rownames(coldata.1)]
#coldata.1 <- column_to_rownames(coldata.1, var="subjid")
# make summarized experiment object
se <- SummarizedExperiment(assays=list(counts=counts2),
                           colData = coldata.1)

# Save
saveRDS(se, "../data/tb_lion_rsubread_se.RDS")
```







